apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  MINIO_EXT_PORT: "${MINIO_EXT_PORT}"
  MINIO_INT_PORT: "${MINIO_INT_PORT}"
  MINIO_UI_EXT_PORT: "${MINIO_UI_EXT_PORT}"
  MINIO_UI_INT_PORT: "${MINIO_UI_INT_PORT}"
  RABBITMQ_EXT_PORT: "${RABBITMQ_EXT_PORT}"
  RABBITMQ_INT_PORT: "${RABBITMQ_INT_PORT}"
  RABBITMQ_UI_EXT_PORT: "${RABBITMQ_UI_EXT_PORT}"
  RABBITMQ_UI_INT_PORT: "${RABBITMQ_UI_INT_PORT}"
  GRPC_BIND_PORT: "${GRPC_BIND_PORT}"
  PORT: "${PORT}"
  BASE_URL: "${BASE_URL}"
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_NAME: "${DB_NAME}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  NODE_ENV: "${NODE_ENV}"
  STRATEGY: "${STRATEGY}"
  JWT_SECRET: "${JWT_SECRET}"
  AWS_REGION: "${AWS_REGION}"
  AWS_S3_BUCKET: "${AWS_S3_BUCKET}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_S3_FORCE_PATH_STYLE: "${AWS_S3_FORCE_PATH_STYLE}"
  FILES_PRESIGN_EXPIRES_IN_SEC: "${FILES_PRESIGN_EXPIRES_IN_SEC}"
  RABBITMQ_URL: "${RABBITMQ_URL}"
  RABBITMQ_PREFETCH: "${RABBITMQ_PREFETCH}"
  RABBITMQ_MAX_ATTEMPTS: "${RABBITMQ_MAX_ATTEMPTS}"
  GRPC_MIN_TIMEOUT_RESPONSE_MS: "${GRPC_MIN_TIMEOUT_RESPONSE_MS}"
  GRPC_MAX_TIMEOUT_RESPONSE_MS: "${GRPC_MAX_TIMEOUT_RESPONSE_MS}"
  GRPC_MAX_COUNT_RETRIES: "${GRPC_MAX_COUNT_RETRIES}"
  RABBITMQ_SIMULATE_CONSUME_ERRORS: "${RABBITMQ_SIMULATE_CONSUME_ERRORS}"
  PAYMENTS_GRPC_URL: "${PAYMENTS_GRPC_URL}"
  MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
  MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
  RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
  RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
data:
  GRPC_TLS_CERT: "${GRPC_TLS_CERT_B64}"
  GRPC_TLS_KEY: "${GRPC_TLS_KEY_B64}"