services:

  app:
    image: order-platform-prod-distroless-runner
    # image: order-platform-prod-runner
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-distroless
      # target: prod
    depends_on:
      postgres:
        condition: service_started
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend

  migrate:
    image: migrate
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    env_file:
      - ./.env
    networks:
      - backend
    volumes:
      - ./src/migrations:/app/src/migrations
      - ./src/seeds:/app/src/seeds
    links:
      - postgres
    depends_on:
      - postgres
      - app

  seed:
    image: seed
    build:
      context: .
      dockerfile: Dockerfile
      target: seeds
    env_file:
      - ./.env
    networks:
      - backend
    volumes:
      - ./src/migrations:/app/src/migrations
      - ./src/seeds:/app/src/seeds
    depends_on:
      - migrate
      - app

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - backend
    volumes:
      - ./pgdata_files_module:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    networks:
      - backend
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_files_module:/data
    depends_on:
      - postgres

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
      - postgres
    restart: 'no'
    networks:
      - backend
    env_file:
      - ./.env
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 ${AWS_ACCESS_KEY_ID:-minioadmin} ${AWS_SECRET_ACCESS_KEY:-minioadmin}; do
        echo 'waiting for minio...';
        sleep 2;
      done;
      mc mb --ignore-existing local/${AWS_S3_BUCKET:-files-private};
      mc anonymous set none local/${AWS_S3_BUCKET:-files-private};
      echo 'minio bucket is ready';
      "

  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user1
      - RABBITMQ_DEFAULT_PASS=pass1
    networks:
      - backend
    env_file:
      - ./.env
    healthcheck:
        test: rabbitmq-diagnostics -q check_running
        interval: 3s
        timeout: 10s
        retries: 5
    ports:
      - ${RABBITMQ_EXT_PORT}:${RABBITMQ_INT_PORT}
      - ${RABBITMQ_UI_EXT_PORT}:${RABBITMQ_UI_INT_PORT}

  payments-grpc:
    image: node:22-alpine
    working_dir: /app
    networks:
      - backend
    env_file:
      - ./.env
    volumes:
      - ./:/app
    ports:
      - ${GRPC_BIND_PORT}:${GRPC_BIND_PORT}
    command: sh -c "corepack enable && npm install && npm run start:payments:dev"

volumes:
  pgdata_files_module:
  minio_files_module:

networks:
  backend: {}
