apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose -f compose.dev.yml convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: minio-init
  name: minio-init
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - " until mc alias set local http://minio:9000 minioadmin minioadmin; do\n  echo 'waiting for minio...';\n  sleep 2;\ndone; mc mb --ignore-existing local/files-private; mc anonymous set none local/files-private; echo 'minio bucket is ready'; echo 'Minio-init Done' && exit 0 "
      envFrom:
        - secretRef:
            name: app-secret
      image: minio/mc:latest
      name: minio-init
  restartPolicy: Never
